import { createSessionService, getAllSessionService, getSessionById } from "../services/sessionService.js";

export const createSessionController = async (req, res)=>{
    try{
        const createdSession = await createSessionService(req.body);
        // req body will be having 
        // {
        //     userId
        //     sessionName
        // }
        return res.status(201).json({
            success:true,
            message:"Session created Successfully",
            data:createdSession,
        })
    }
    catch(error){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error.status){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}

export const getAllSessionController = async(req, res)=>{
    try{
        const allSession = await getAllSessionService();
        return res.status(200).json({
            success : true,
            message : "Fetched all the session",
            data: allSession
        })
    }
    catch(error){
        console.log("error at the controller layer in getting all the session");
        res.status(500).json({
            success: false,
            error
        })
    }
};

export const getSessionByIdController = async(req, res)=>{
    try{
        const sessionId = req.params.id;

        const currSession = await getSessionById(sessionId);
        return res.status(200).json({
            success : true,
            message : "Session fetched successfully",
            data: currSession
        })
    }
    catch(error){
        console.log("error at the controller layer in getting the session by Id" );
        res.status(500).json({
            success: false,
            error
        })
    }
};